// Generated by gencpp from file object_service/DemoRequest.msg
// DO NOT EDIT!


#ifndef OBJECT_SERVICE_MESSAGE_DEMOREQUEST_H
#define OBJECT_SERVICE_MESSAGE_DEMOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace object_service
{
template <class ContainerAllocator>
struct DemoRequest_
{
  typedef DemoRequest_<ContainerAllocator> Type;

  DemoRequest_()
    : command(0)
    , name()
    , num(0.0)
    , text()  {
    }
  DemoRequest_(const ContainerAllocator& _alloc)
    : command(0)
    , name(_alloc)
    , num(0.0)
    , text(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _command_type;
  _command_type command;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef float _num_type;
  _num_type num;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _text_type;
  _text_type text;





  typedef boost::shared_ptr< ::object_service::DemoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_service::DemoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DemoRequest_

typedef ::object_service::DemoRequest_<std::allocator<void> > DemoRequest;

typedef boost::shared_ptr< ::object_service::DemoRequest > DemoRequestPtr;
typedef boost::shared_ptr< ::object_service::DemoRequest const> DemoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_service::DemoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_service::DemoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::object_service::DemoRequest_<ContainerAllocator1> & lhs, const ::object_service::DemoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command &&
    lhs.name == rhs.name &&
    lhs.num == rhs.num &&
    lhs.text == rhs.text;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::object_service::DemoRequest_<ContainerAllocator1> & lhs, const ::object_service::DemoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace object_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::object_service::DemoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_service::DemoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_service::DemoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_service::DemoRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_service::DemoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_service::DemoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_service::DemoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1177a9a44eb0b4df4d6dc031be0f4061";
  }

  static const char* value(const ::object_service::DemoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1177a9a44eb0b4dfULL;
  static const uint64_t static_value2 = 0x4d6dc031be0f4061ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_service::DemoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_service/DemoRequest";
  }

  static const char* value(const ::object_service::DemoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_service::DemoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# header\n"
"uint8 command\n"
"string name\n"
"# body\n"
"float32 num\n"
"string text\n"
;
  }

  static const char* value(const ::object_service::DemoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_service::DemoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.name);
      stream.next(m.num);
      stream.next(m.text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DemoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_service::DemoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_service::DemoRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "num: ";
    Printer<float>::stream(s, indent + "  ", v.num);
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_SERVICE_MESSAGE_DEMOREQUEST_H
